MERGE INTO PUBLIC.RATINGS (RATING_ID, RATING_NAME) VALUES (1, 'G');
MERGE INTO PUBLIC.RATINGS (RATING_ID, RATING_NAME) VALUES (2, 'PG');
MERGE INTO PUBLIC.RATINGS (RATING_ID, RATING_NAME) VALUES (3, 'PG-13');
MERGE INTO PUBLIC.RATINGS (RATING_ID, RATING_NAME) VALUES (4, 'R');
MERGE INTO PUBLIC.RATINGS (RATING_ID, RATING_NAME) VALUES (5, 'NC-17');

MERGE INTO PUBLIC.GENRE (GENRE_ID, NAME) VALUES (6, 'Боевик');
MERGE INTO PUBLIC.GENRE (GENRE_ID, NAME) VALUES (5, 'Документальный');
MERGE INTO PUBLIC.GENRE (GENRE_ID, NAME) VALUES (2, 'Драма');
MERGE INTO PUBLIC.GENRE (GENRE_ID, NAME) VALUES (1, 'Комедия');
MERGE INTO PUBLIC.GENRE (GENRE_ID, NAME) VALUES (3, 'Мультфильм');
MERGE INTO PUBLIC.GENRE (GENRE_ID, NAME) VALUES (4, 'Триллер');

MERGE INTO PUBLIC.FILMS (FILM_ID, NAME, DESCRIPTION, RELEASE_DATE, DURATION) VALUES (1, 'Карты, деньги и два дымящихся ствола', null, '1998-10-23', 107);
MERGE INTO PUBLIC.FILMS (FILM_ID, NAME, DESCRIPTION, RELEASE_DATE, DURATION) VALUES (2, 'Бриллиантовая рука', null, '1969-04-28', 100);
MERGE INTO PUBLIC.FILMS (FILM_ID, NAME, DESCRIPTION, RELEASE_DATE, DURATION) VALUES (3, 'Побег из Шоушенка', null, '1994-09-10', 142);
MERGE INTO PUBLIC.FILMS (FILM_ID, NAME, DESCRIPTION, RELEASE_DATE, DURATION) VALUES (4, 'Молчание ягнят', null, '1991-01-30', 118);
MERGE INTO PUBLIC.FILMS (FILM_ID, NAME, DESCRIPTION, RELEASE_DATE, DURATION) VALUES (5, 'Человек-паук', null, '2002-04-30', 121);

MERGE INTO PUBLIC.USERS (USER_ID, EMAIL, LOGIN, NAME, BIRTHDAY) VALUES (1, 'one@mail.ru', 'onelogin', 'first name', '2002-10-18');
MERGE INTO PUBLIC.USERS (USER_ID, EMAIL, LOGIN, NAME, BIRTHDAY) VALUES (2, 'second@gmail.com', 'secondlogin', 'second name', '1998-07-08');
MERGE INTO PUBLIC.USERS (USER_ID, EMAIL, LOGIN, NAME, BIRTHDAY) VALUES (3, 'third@yandex.ru', 'thirdlogin', 'third name', '2012-11-14');

MERGE INTO PUBLIC.FILMS (FILM_ID, NAME, DESCRIPTION, RELEASE_DATE, DURATION, RATING_ID) VALUES (1, 'Карты, деньги и два дымящихся ствола', null, '1998-10-23', 107, 4);
MERGE INTO PUBLIC.FILMS (FILM_ID, NAME, DESCRIPTION, RELEASE_DATE, DURATION, RATING_ID) VALUES (2, 'Бриллиантовая рука', null, '1969-04-28', 100, 1);
MERGE INTO PUBLIC.FILMS (FILM_ID, NAME, DESCRIPTION, RELEASE_DATE, DURATION, RATING_ID) VALUES (3, 'Побег из Шоушенка', null, '1994-09-10', 142, 3);
MERGE INTO PUBLIC.FILMS (FILM_ID, NAME, DESCRIPTION, RELEASE_DATE, DURATION, RATING_ID) VALUES (4, 'Молчание ягнят', null, '1991-01-30', 118, 5);
MERGE INTO PUBLIC.FILMS (FILM_ID, NAME, DESCRIPTION, RELEASE_DATE, DURATION, RATING_ID) VALUES (5, 'Человек-паук', null, '2002-04-30', 121, 2);

MERGE INTO PUBLIC.FILM_GENRE (FILM_GENRE_ID, FILM_ID, GENRE_ID) VALUES (2, 1, 4);
MERGE INTO PUBLIC.FILM_GENRE (FILM_GENRE_ID, FILM_ID, GENRE_ID) VALUES (1, 1, 6);
MERGE INTO PUBLIC.FILM_GENRE (FILM_GENRE_ID, FILM_ID, GENRE_ID) VALUES (3, 2, 1);
MERGE INTO PUBLIC.FILM_GENRE (FILM_GENRE_ID, FILM_ID, GENRE_ID) VALUES (4, 3, 2);
MERGE INTO PUBLIC.FILM_GENRE (FILM_GENRE_ID, FILM_ID, GENRE_ID) VALUES (5, 4, 4);
MERGE INTO PUBLIC.FILM_GENRE (FILM_GENRE_ID, FILM_ID, GENRE_ID) VALUES (7, 5, 1);
MERGE INTO PUBLIC.FILM_GENRE (FILM_GENRE_ID, FILM_ID, GENRE_ID) VALUES (6, 5, 6);

MERGE INTO PUBLIC.FILM_LIKES (ID, FILM_ID, USER_ID) VALUES (2, 1, 2);
MERGE INTO PUBLIC.FILM_LIKES (ID, FILM_ID, USER_ID) VALUES (1, 2, 1);
MERGE INTO PUBLIC.FILM_LIKES (ID, FILM_ID, USER_ID) VALUES (3, 2, 2);
MERGE INTO PUBLIC.FILM_LIKES (ID, FILM_ID, USER_ID) VALUES (4, 3, 2);
MERGE INTO PUBLIC.FILM_LIKES (ID, FILM_ID, USER_ID) VALUES (5, 3, 3);
MERGE INTO PUBLIC.FILM_LIKES (ID, FILM_ID, USER_ID) VALUES (6, 5, 1);
MERGE INTO PUBLIC.FILM_LIKES (ID, FILM_ID, USER_ID) VALUES (7, 5, 2);
MERGE INTO PUBLIC.FILM_LIKES (ID, FILM_ID, USER_ID) VALUES (8, 5, 3);

MERGE INTO PUBLIC.USER_FRIENDS (USER_FRIENDS_ID, USER_ID, FRIEND_ID, CONFIRMED_BY_FRIEND) VALUES (1, 2, 3, true);
MERGE INTO PUBLIC.USER_FRIENDS (USER_FRIENDS_ID, USER_ID, FRIEND_ID, CONFIRMED_BY_FRIEND) VALUES (2, 3, 2, true);
MERGE INTO PUBLIC.USER_FRIENDS (USER_FRIENDS_ID, USER_ID, FRIEND_ID, CONFIRMED_BY_FRIEND) VALUES (3, 1, 3, false);
MERGE INTO PUBLIC.USER_FRIENDS (USER_FRIENDS_ID, USER_ID, FRIEND_ID, CONFIRMED_BY_FRIEND) VALUES (4, 2, 1, false);
